### ISSUE TITLE
[Working] Improved Curse of Weakness gives normal values

### ISSUE THREAD

**Issue by famousgh** [sennawins/wpsg#6]
![wowscrnshot_042317_120946](https://cloud.githubusercontent.com/assets/27897902/25316627/8c282096-281f-11e7-8723-1f7388b0f39e.jpg)

rank 9 improved curse of weakness reduces targets attack power by 573, debuff tooltip displays unimproved value of 478

**Comment by sennawins** [comment]
Just tested, it's working, tooltip error
